spring.application.name=eureka
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/eureka
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gpeicic2@gmail.com
spring.mail.password=ktjqsqobeybscijb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=ovdje_ides_neki_dugacki_random_string_minimalno_32_znaka
jwt.expiration=86400000

encryption.secret=mojSuperTajniKljuc32CharaDugi!!
encryption.salt=deadbeefdeadbeef
